version: "3"

volumes:
  postgres_data: {}
  postgres_backup: {}
  staticfiles: {}

services:
  backend:
    container_name: django
    build: ./backend
    restart: always
    volumes:
      - ./backend/:/backend # maps host diretory to internal container directory
      - staticfiles:/backend/staticfiles
    working_dir: /backend/
    command: sh entrypoint.sh
  # db:
  #   container_name: postgres
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - postgres_backup:/backups

  # frontend:
  #   container_name: react
  #   image: node:12.16.1
  #   command: sh entrypoint.sh
  #   working_dir: /frontend
  #   volumes:
  #     - ./frontend/:/frontend
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/backend/staticfiles
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
