version: "3"

volumes:
  postgres_data: {}
  postgres_backup: {}
  staticfiles: {}

services:
  backend:
    container_name: django
    build: ./backend # first build os enviroment
    command: sh entrypoint.sh # then run app specific commands
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/backend # maps host diretory to internal container directory
      - staticfiles:/backend/staticfiles
    working_dir: /backend/
    env_file:
      - ./development.env # change this to development / prodcution env file. Remember to change .gitignore
    restart: always
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file:
      - ./db.env # remember to change credentials and .gitignore file

  # frontend:
  #   container_name: react
  #   image: node:12.16.1
  #   command: sh entrypoint.sh
  #   working_dir: /frontend
  #   volumes:
  #     - ./frontend/:/frontend
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/backend/staticfiles
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
