version: "3"

services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend/:/backend # maps host diretory to internal container directory
    working_dir: /backend/
    command: sh entrypoint.sh
  frontend:
    image: node:12.16.1
    command: sh entrypoint.sh
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
